### ISSUE TITLE
how to pin specific aws sam verision?

### ISSUE THREAD

**Issue by rakesh-saiga** [aws-samples/aws-sam-github-actions-example#3]
How does the gihub action file installs SAM her e in this ? is this pre-installed on ubuntu ?

if i want to use a specific aws sam version, how do i do it ?

**Comment by spitzzz** [comment]
To do this you would need to change the image used by the workflow. The current image being used is specified as `ubuntu-latest` in the workflows here.

Primary workflow: https://github.com/aws-samples/aws-sam-github-actions-example/blob/main/.github/workflows/primary.yml#L8

Secondary workflow: https://github.com/aws-samples/aws-sam-github-actions-example/blob/main/.github/workflows/secondary.yml#L8

SAM is pre-installed on this image, as seen in the documentation here:
https://github.com/actions/virtual-environments/blob/ubuntu20/20210309.1/images/linux/Ubuntu2004-README.md

You could potentially build your own image with the specified version of SAM you would like to use, or create your own custom logic to potentially uninstall/reinstall SAM with a specified version.

**Comment by spitzzz** [comment]
@rakesh-saiga check this out: https://github.com/aws-actions/setup-sam

This repo is not currently using this, but may add this in the future.

**Comment by rakesh-saiga** [comment]
@spitzzz Thanks so much, this is awesome
