### ISSUE TITLE
[ISSUE] Already existing S3 bucket makes deployment fail

### ISSUE THREAD

**Issue by nerg4l** [aws-samples/aws-sam-github-actions-example#5]
**Describe the bug**
In its current state `primary.yml` cannot be reused because a second run on the same branch will fail when it tries to create the S3 bucket.

**To Reproduce**
1. Trigger `primary.yml` with push on `main`
2. Make changes on `main`
3. Trigger `primary.yml` with push on `main`
4. See "Bucket name already exists" error

**Expected behavior**
Provided example should be reusable. In it current state one can only trigger the deployment once without removing the created bucket.

**Additional context**
Deployment process contains the following code: `aws s3 mb s3://${{ steps.vars.outputs.environment }}`. This command fails if the bucket already exists.

**Comment by spitzzz** [comment]
Hi @nerg4l,

Thanks for bringing this to our attention. The intent of this repository is to serve as an example, as you may have seen in the code, we build the bucket name using the `environment` variable that is built like so:
```
ENVIRONMENT=$BRANCH-$REPOSITORY-${{ secrets.AWS_REGION }}
```

As you can see - ultimately the repository name is what would make this unique. So as an interim solution, if you simply use a different repository name that will solve your issue.

It would certainly be nice if this was re-usable out of the box though (through forks as you are experiencing I suspect), so I will likely be doing one of the following:

1. Updating the documentation with instructions on how to resolve this.
2. Adding use of a new variable to make this unique, or coming up with another method.

**Comment by nerg4l** [comment]
Hello @spitzzz,

**Less rushed steps to reproduce:**

1. Create a new project using this repo as a template.
2. Push code.
3. GitHub Actions deployment succeeds. (GREEN)
4. Change any part of the code.
5. Push code.
6. GitHub Actions deployment fails. (RED)

The error in the logs will be "Bucket name already exists".

**Comments on your ideas:**

> Updating the documentation with instructions on how to resolve this.

One solution would be to pre request an already existing S3 bucket and the name of the bucket could be a required env variable.

> Adding use of a new variable to make this unique, or coming up with another method.

I'm not familiar with best practices but I assume one bucket per project should be enough. As an attempt to fix the deployment I first check if the bucket already exists and create it if it doesn't.

```
          # Create S3 Bucket to store code
          aws s3 mb s3://${{ steps.vars.outputs.environment }}
```

replaced with

```
          # Create S3 Bucket to store code
          aws s3api head-bucket --bucket "${{ steps.vars.outputs.environment }}" 2>/dev/null \
            || aws s3 mb s3://${{ steps.vars.outputs.environment }}
```

**Comment by spitzzz** [comment]
Thanks @nerg4l  for the fix, added your change in this PR:
https://github.com/aws-samples/aws-sam-github-actions-example/pull/9
